### ISSUE TITLE
Cifar10-Imagenet_crop

### ISSUE THREAD

**Issue by sudipansaha** [zaeemzadeh/OOD#3]
Hi,

Are the parameters in main.sh the ones used in paper? With main.sh, for Cifar10-Imagenet_crop I obtained the following:

FPR @95TPR: 0.1878
Detection Error: 0.1113
AUC:  0.9526946150000001

**Comment by zaeemzadeh** [comment]
Hi, As mentioned in the paper, we used [this](https://github.com/wjmaddox/swa_gaussian) method for extracting the Monte Carlo samples, not dropout.
