### ISSUE TITLE
I did not find any code related to SWAG in this repo. Right?

### ISSUE THREAD

**Issue by zoezhou1999** [zaeemzadeh/OOD#4]
Hello,
I did not find any code related to SWAG in this repo.
Please correct me if I am wrong. Thank you!

**Comment by zaeemzadeh** [comment]
Hi. Yes, the code estimates the probabilities using drop-out as the MC sampling ([this paper](http://proceedings.mlr.press/v48/gal16.html)).  To use SWAG you should use the [SWAG repo](https://github.com/wjmaddox/swa_gaussian), alongside our model files.
